### ISSUE TITLE
update stuck

### ISSUE THREAD

**Issue by millette** [watson/npm-dependency-db#1]
I ran ```npm-dependency-db --update``` and it got to 367715/367716 and 361618/367716 and seemd to stall. I hit CTRL-C and restarted it where it moved a little bit but stalled again. CTRL-C and repeat a few times, now it's stuck at:
```
cache location: /home/millette/.npm-dependency-db
downloading [------------------------------------------] (0/1)
processing  [------------------------------------------] (0/5570)
```

I can provide more info; the app directory has over 2.5 GiB and 1300 files.

**Comment by watson** [comment]
@millette thanks for the report. I probably have an off-by-one error somewhere or maybe I'm not correctly handling updates to npm, while the update is running, or I'm simply not closing the stream correctly. I'll look into it 😃 

In any case: You are most likely only missing the latest changes to npm that have occurred within the last few hours. So you should be able to run a query now with the data you have so far.

**Comment by millette** [comment]
Thanks, it works, although I had to CTRL-C the (stalled) --update process because of the LOCK file. Running the upgrade, I'm still stalled at

```
cache location: /home/millette/.npm-dependency-db
downloading [------------------------------------------] (0/168)
processing  [------------------------------------------] (0/5758)
```

Will stay tuned.

**Comment by watson** [comment]
@millette I just fixed the issue with the processing number being wrong (released as v1.1.2). There were an issue that could miss a few updates from npm, so to ensure that your local cache is 100% correct, I recommend deleting it and running the update command again.

I'm still working on the other stuff you reported 😃

**Comment by millette** [comment]
Thanks @watson. I deleted the cache, updated and gave it another shot:

```
cache location: /home/millette/.npm-dependency-db
downloading [=========================================-] (367715/373386)
processing  [========================================--] (362145/373386)
^C
millette@david:~$ npm-dependency-db --update
cache location: /home/millette/.npm-dependency-db
downloading [------------------------------------------] (0/5671)
processing  [------------------------------------------] (0/11240)
```

And it stalled there. Using node 4.6.1. Let me know if you need more info or logs.

**Comment by watson** [comment]
Found the bug - It turned out that hypercore (the replication technology I use behind the scenes) have a default size limit per object of 5mb and that one of the npm change-sets was over 5mb, so it couldn't sync it.

This have now been fixed up-stream, so all you need to do is reinstall npm-dependency-db (no need to delete your local cache any more) and it should automatically update the updated sub-dependency:

```
npm install npm-dependency-db -g
```

And then run the update command again:

```
npm-dependency-db --update
```

And it should now sync the remaining packages

**Comment by watson** [comment]
... I also fixed a few bugs and made some improvements to this module - so there's a new version out (v1.2.1)

**Comment by millette** [comment]
Let it ran for a while... it stalled, no apparent activity. After a minute or so I restarted it:

```
downloading [=======================-------------------] (3181/5671) 0 B/s
processing  [================================----------] (8750/11240) 0.0/sec
^C
millette@david:~$ npm-dependency-db --update
cache location: /home/millette/.npm-dependency-db
downloading [==========================================] (2490/2490) 312 KB/s
processing  [==========================================] (2490/2490) 1.6/sec
```

Success! Thanks :-)

**Comment by watson** [comment]
@millette I think all the kinks have been ironed out by now. If not, feel free to reopen or create a new issue if you find something else 😃
