### ISSUE TITLE
live option and locks

### ISSUE THREAD

**Issue by millette** [watson/npm-dependency-db#3]
Just tried the 1.3 release with the --live options. Thanks!

I was hoping I could let it run with --live and still be able to query it. But like a normal --update usage, a lock prevents queries while it's updating.

For example:
```
$ npm-dependency-db hapijs-status-monitor
cache location: /home/millette/.npm-dependency-db
Looking up hapijs-status-monitor * dependants...

events.js:141
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: lock /home/millette/.npm-dependency-db/LOCK: Resource temporarily unavailable
    at /home/millette/n/lib/node_modules/npm-dependency-db/node_modules/levelup/lib/levelup.js:119:34
    at /home/millette/n/lib/node_modules/npm-dependency-db/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

It works as expected when I quit the update (live or normal).

Perhaps it could be a "semi-live" option, releasing the lock and restarting itself every 10 minutes or so to actually run the updates? This way npm-dependency-db MOD would almost always work. Just thinking out loud...

**Comment by watson** [comment]
@millette didn't consider that - thanks for bringing it up 😃 I've published a fix as v1.4.0
