### ISSUE TITLE
Update notifier

### ISSUE THREAD

**Issue by millette** [watson/npm-dependency-db#4]
I'm willing to write a patch that would depend on https://github.com/yeoman/update-notifier to

> Inform users of your package of updates in a non-intrusive way.

Would you accept this new feature?

**Comment by watson** [comment]
Thanks for asking 😃 I'm not a big fan of those messages my self as I find them fairly disruptive, so I'd rather not have it

**Comment by millette** [comment]
Although we could add something like the following to your readme (citing <https://github.com/yeoman/update-notifier#user-settings>):

### User settings

Users of your module have the ability to opt-out of the update notifier by changing the `optOut` property to `true` in `~/.config/configstore/update-notifier-[your-module-name].yml`. The path is available in `notifier.config.path`.

Users can also opt-out by [setting the environment variable](https://github.com/sindresorhus/guides/blob/master/set-environment-variables.md) `NO_UPDATE_NOTIFIER` with any value or by using the `--no-update-notifier` flag on a per run basis.

------

Or simply close the issue, I don't think I have more arguments ;-)
