### ISSUE TITLE
Live update exits

### ISSUE THREAD

**Issue by millette** [watson/npm-dependency-db#6]
I upgraded to 6.x and notice --update --live ends with exit code 1 when it catches up instead of staying live.

I check the source, found with it received the "end" signal:
https://github.com/watson/npm-dependency-db/commit/231a304edd7e373cc78d86de3393cee57e6ecad7 (3 month old code)

But I don't understand why it actually ends when it was working fine a few versions ago.

**Comment by watson** [comment]
Thanks for reporting 😃 It's been fixed in v6.0.4
